//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 AddDetail 的本地化字符串。
        /// </summary>
        public static string Button_AddDetail {
            get {
                return ResourceManager.GetString("Button_AddDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adjust 的本地化字符串。
        /// </summary>
        public static string Button_Adjust {
            get {
                return ResourceManager.GetString("Button_Adjust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AdjustGI 的本地化字符串。
        /// </summary>
        public static string Button_AdjustGI {
            get {
                return ResourceManager.GetString("Button_AdjustGI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AdjustGR 的本地化字符串。
        /// </summary>
        public static string Button_AdjustGR {
            get {
                return ResourceManager.GetString("Button_AdjustGR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All Adjust 的本地化字符串。
        /// </summary>
        public static string Button_AllAdjust {
            get {
                return ResourceManager.GetString("Button_AllAdjust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back 的本地化字符串。
        /// </summary>
        public static string Button_Back {
            get {
                return ResourceManager.GetString("Button_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BackFlush 的本地化字符串。
        /// </summary>
        public static string Button_BackFlush {
            get {
                return ResourceManager.GetString("Button_BackFlush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BomDetail 的本地化字符串。
        /// </summary>
        public static string Button_BomDetail {
            get {
                return ResourceManager.GetString("Button_BomDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel the shipment 的本地化字符串。
        /// </summary>
        public static string Button_Cancellations {
            get {
                return ResourceManager.GetString("Button_Cancellations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change Password 的本地化字符串。
        /// </summary>
        public static string Button_ChangePassword {
            get {
                return ResourceManager.GetString("Button_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check 的本地化字符串。
        /// </summary>
        public static string Button_Check {
            get {
                return ResourceManager.GetString("Button_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Complete 的本地化字符串。
        /// </summary>
        public static string Button_Complete {
            get {
                return ResourceManager.GetString("Button_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Concession 的本地化字符串。
        /// </summary>
        public static string Button_Concession {
            get {
                return ResourceManager.GetString("Button_Concession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        public static string Button_Confirm {
            get {
                return ResourceManager.GetString("Button_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure to {0} 的本地化字符串。
        /// </summary>
        public static string Button_ConfirmOperation {
            get {
                return ResourceManager.GetString("Button_ConfirmOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create 的本地化字符串。
        /// </summary>
        public static string Button_Create {
            get {
                return ResourceManager.GetString("Button_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CreatePickList 的本地化字符串。
        /// </summary>
        public static string Button_CreatePickList {
            get {
                return ResourceManager.GetString("Button_CreatePickList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CreateRequisitionList 的本地化字符串。
        /// </summary>
        public static string Button_CreateRequisitionList {
            get {
                return ResourceManager.GetString("Button_CreateRequisitionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeleteDetail 的本地化字符串。
        /// </summary>
        public static string Button_DeleteDetail {
            get {
                return ResourceManager.GetString("Button_DeleteDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeleteResult 的本地化字符串。
        /// </summary>
        public static string Button_DeleteResult {
            get {
                return ResourceManager.GetString("Button_DeleteResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DistributionLableCancel 的本地化字符串。
        /// </summary>
        public static string Button_DistributionLabel_Cancel {
            get {
                return ResourceManager.GetString("Button_DistributionLabel_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DistributionLabel_Export 的本地化字符串。
        /// </summary>
        public static string Button_DistributionLabel_Export {
            get {
                return ResourceManager.GetString("Button_DistributionLabel_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Button_DistributionLabel_Print 的本地化字符串。
        /// </summary>
        public static string Button_DistributionLabel_Print {
            get {
                return ResourceManager.GetString("Button_DistributionLabel_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        public static string Button_Edit {
            get {
                return ResourceManager.GetString("Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        public static string Button_Export {
            get {
                return ResourceManager.GetString("Button_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Detail 的本地化字符串。
        /// </summary>
        public static string Button_ExportDetail {
            get {
                return ResourceManager.GetString("Button_ExportDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Finance Calendar 的本地化字符串。
        /// </summary>
        public static string Button_FinanceCalendar {
            get {
                return ResourceManager.GetString("Button_FinanceCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Freeze 的本地化字符串。
        /// </summary>
        public static string Button_Freeze {
            get {
                return ResourceManager.GetString("Button_Freeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import 的本地化字符串。
        /// </summary>
        public static string Button_Import {
            get {
                return ResourceManager.GetString("Button_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Judge 的本地化字符串。
        /// </summary>
        public static string Button_Judge {
            get {
                return ResourceManager.GetString("Button_Judge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JudgeQualify 的本地化字符串。
        /// </summary>
        public static string Button_JudgeQualify {
            get {
                return ResourceManager.GetString("Button_JudgeQualify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JudgeReject 的本地化字符串。
        /// </summary>
        public static string Button_JudgeReject {
            get {
                return ResourceManager.GetString("Button_JudgeReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KBOrderBomDet 的本地化字符串。
        /// </summary>
        public static string Button_KBOrderBomDet {
            get {
                return ResourceManager.GetString("Button_KBOrderBomDet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MaterialIn 的本地化字符串。
        /// </summary>
        public static string Button_MaterialIn {
            get {
                return ResourceManager.GetString("Button_MaterialIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New 的本地化字符串。
        /// </summary>
        public static string Button_New {
            get {
                return ResourceManager.GetString("Button_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OffLine 的本地化字符串。
        /// </summary>
        public static string Button_OffLine {
            get {
                return ResourceManager.GetString("Button_OffLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 online 的本地化字符串。
        /// </summary>
        public static string Button_online {
            get {
                return ResourceManager.GetString("Button_online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OutToDetermine 的本地化字符串。
        /// </summary>
        public static string Button_OutToDetermine {
            get {
                return ResourceManager.GetString("Button_OutToDetermine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pause 的本地化字符串。
        /// </summary>
        public static string Button_Pause {
            get {
                return ResourceManager.GetString("Button_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pick 的本地化字符串。
        /// </summary>
        public static string Button_Pick {
            get {
                return ResourceManager.GetString("Button_Pick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pick Up 的本地化字符串。
        /// </summary>
        public static string Button_PickUp {
            get {
                return ResourceManager.GetString("Button_PickUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preview 的本地化字符串。
        /// </summary>
        public static string Button_Preview {
            get {
                return ResourceManager.GetString("Button_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print 的本地化字符串。
        /// </summary>
        public static string Button_Print {
            get {
                return ResourceManager.GetString("Button_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PrintCard 的本地化字符串。
        /// </summary>
        public static string Button_PrintCard {
            get {
                return ResourceManager.GetString("Button_PrintCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PrintCardLabel 的本地化字符串。
        /// </summary>
        public static string Button_PrintCardLabel {
            get {
                return ResourceManager.GetString("Button_PrintCardLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Put Away 的本地化字符串。
        /// </summary>
        public static string Button_PutAway {
            get {
                return ResourceManager.GetString("Button_PutAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Receive 的本地化字符串。
        /// </summary>
        public static string Button_Receive {
            get {
                return ResourceManager.GetString("Button_Receive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Receive 的本地化字符串。
        /// </summary>
        public static string Button_Receive_Distrabution {
            get {
                return ResourceManager.GetString("Button_Receive_Distrabution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        public static string Button_Refresh {
            get {
                return ResourceManager.GetString("Button_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Requisition Detail 的本地化字符串。
        /// </summary>
        public static string Button_RequisitionDetail {
            get {
                return ResourceManager.GetString("Button_RequisitionDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Return 的本地化字符串。
        /// </summary>
        public static string Button_Return {
            get {
                return ResourceManager.GetString("Button_Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Routing 的本地化字符串。
        /// </summary>
        public static string Button_Routing {
            get {
                return ResourceManager.GetString("Button_Routing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Detail 的本地化字符串。
        /// </summary>
        public static string Button_SaveDetail {
            get {
                return ResourceManager.GetString("Button_SaveDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Master 的本地化字符串。
        /// </summary>
        public static string Button_SaveMaster {
            get {
                return ResourceManager.GetString("Button_SaveMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        public static string Button_Search {
            get {
                return ResourceManager.GetString("Button_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Button_SearchExport 的本地化字符串。
        /// </summary>
        public static string Button_SearchExport {
            get {
                return ResourceManager.GetString("Button_SearchExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ship 的本地化字符串。
        /// </summary>
        public static string Button_Ship {
            get {
                return ResourceManager.GetString("Button_Ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        public static string Button_Start {
            get {
                return ResourceManager.GetString("Button_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        public static string Button_Start_Production {
            get {
                return ResourceManager.GetString("Button_Start_Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StartEmptyVanOrder 的本地化字符串。
        /// </summary>
        public static string Button_StartEmptyVanOrder {
            get {
                return ResourceManager.GetString("Button_StartEmptyVanOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit 的本地化字符串。
        /// </summary>
        public static string Button_Submit {
            get {
                return ResourceManager.GetString("Button_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transfer 的本地化字符串。
        /// </summary>
        public static string Button_Transfer {
            get {
                return ResourceManager.GetString("Button_Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UnFreeze 的本地化字符串。
        /// </summary>
        public static string Button_UnFreeze {
            get {
                return ResourceManager.GetString("Button_UnFreeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload 的本地化字符串。
        /// </summary>
        public static string Button_Upload {
            get {
                return ResourceManager.GetString("Button_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Code 的本地化字符串。
        /// </summary>
        public static string Common_Code {
            get {
                return ResourceManager.GetString("Common_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Date 的本地化字符串。
        /// </summary>
        public static string Common_CreateDate {
            get {
                return ResourceManager.GetString("Common_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create User 的本地化字符串。
        /// </summary>
        public static string Common_CreateUserName {
            get {
                return ResourceManager.GetString("Common_CreateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        public static string Common_Description {
            get {
                return ResourceManager.GetString("Common_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End Time 的本地化字符串。
        /// </summary>
        public static string Common_EndTime {
            get {
                return ResourceManager.GetString("Common_EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last Modify Date 的本地化字符串。
        /// </summary>
        public static string Common_LastModifyDate {
            get {
                return ResourceManager.GetString("Common_LastModifyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last Modify User 的本地化字符串。
        /// </summary>
        public static string Common_LastModifyUserName {
            get {
                return ResourceManager.GetString("Common_LastModifyUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Region 的本地化字符串。
        /// </summary>
        public static string Common_Region {
            get {
                return ResourceManager.GetString("Common_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Time 的本地化字符串。
        /// </summary>
        public static string Common_StartTime {
            get {
                return ResourceManager.GetString("Common_StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To 的本地化字符串。
        /// </summary>
        public static string Common_To {
            get {
                return ResourceManager.GetString("Common_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        public static string Common_Type {
            get {
                return ResourceManager.GetString("Common_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        public static string Export_No {
            get {
                return ResourceManager.GetString("Export_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        public static string Export_Yes {
            get {
                return ResourceManager.GetString("Export_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 False 的本地化字符串。
        /// </summary>
        public static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DispalyType 的本地化字符串。
        /// </summary>
        public static string Grid_DispalyType {
            get {
                return ResourceManager.GetString("Grid_DispalyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detail 的本地化字符串。
        /// </summary>
        public static string Grid_DispalyType_Detail {
            get {
                return ResourceManager.GetString("Grid_DispalyType_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Summary 的本地化字符串。
        /// </summary>
        public static string Grid_DispalyType_Summary {
            get {
                return ResourceManager.GetString("Grid_DispalyType_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Batch Import Successful . 的本地化字符串。
        /// </summary>
        public static string ImportSuccess_BatchImportSuccessful {
            get {
                return ResourceManager.GetString("ImportSuccess_BatchImportSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Site 的本地化字符串。
        /// </summary>
        public static string Login_SiteId {
            get {
                return ResourceManager.GetString("Login_SiteId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        public static string Permission_Description {
            get {
                return ResourceManager.GetString("Permission_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Role has been added successfully. 的本地化字符串。
        /// </summary>
        public static string PermissionGroup_Added {
            get {
                return ResourceManager.GetString("PermissionGroup_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PermissionGroup  Name 的本地化字符串。
        /// </summary>
        public static string PermissionGroup_Code {
            get {
                return ResourceManager.GetString("PermissionGroup_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Role has been Deleted successfully. 的本地化字符串。
        /// </summary>
        public static string PermissionGroup_Deleted {
            get {
                return ResourceManager.GetString("PermissionGroup_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PermissionGroup  Description 的本地化字符串。
        /// </summary>
        public static string PermissionGroup_Desc {
            get {
                return ResourceManager.GetString("PermissionGroup_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit PermissionGroup 的本地化字符串。
        /// </summary>
        public static string PermissionGroup_Edit_Title {
            get {
                return ResourceManager.GetString("PermissionGroup_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Role has been Updated successfully. 的本地化字符串。
        /// </summary>
        public static string PermissionGroup_Updated {
            get {
                return ResourceManager.GetString("PermissionGroup_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SapOrderType 的本地化字符串。
        /// </summary>
        public static string SapOrderType {
            get {
                return ResourceManager.GetString("SapOrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 True 的本地化字符串。
        /// </summary>
        public static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
    }
}
