//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.TMS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TransportOrder {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TransportOrder() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.TMS.TransportOrder", typeof(TransportOrder).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 送货单号.
        /// </summary>
        public static string TransportOrderDetail_IpNo {
            get {
                return ResourceManager.GetString("TransportOrderDetail_IpNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账单地址.
        /// </summary>
        public static string TransportOrderMaster_BillAddress {
            get {
                return ResourceManager.GetString("TransportOrderMaster_BillAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 承运商.
        /// </summary>
        public static string TransportOrderMaster_Carrier {
            get {
                return ResourceManager.GetString("TransportOrderMaster_Carrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 承运商描述.
        /// </summary>
        public static string TransportOrderMaster_CarrierName {
            get {
                return ResourceManager.GetString("TransportOrderMaster_CarrierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 驾驶员.
        /// </summary>
        public static string TransportOrderMaster_Driver {
            get {
                return ResourceManager.GetString("TransportOrderMaster_Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 驾驶员手机.
        /// </summary>
        public static string TransportOrderMaster_DriverMobilePhone {
            get {
                return ResourceManager.GetString("TransportOrderMaster_DriverMobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 行驶证号.
        /// </summary>
        public static string TransportOrderMaster_DrivingNo {
            get {
                return ResourceManager.GetString("TransportOrderMaster_DrivingNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外部单号.
        /// </summary>
        public static string TransportOrderMaster_ExternalOrderNo {
            get {
                return ResourceManager.GetString("TransportOrderMaster_ExternalOrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 运输路线.
        /// </summary>
        public static string TransportOrderMaster_Flow {
            get {
                return ResourceManager.GetString("TransportOrderMaster_Flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 运输路线描述.
        /// </summary>
        public static string TransportOrderMaster_FlowDescription {
            get {
                return ResourceManager.GetString("TransportOrderMaster_FlowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动释放.
        /// </summary>
        public static string TransportOrderMaster_IsAutoRelease {
            get {
                return ResourceManager.GetString("TransportOrderMaster_IsAutoRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动开始.
        /// </summary>
        public static string TransportOrderMaster_IsAutoStart {
            get {
                return ResourceManager.GetString("TransportOrderMaster_IsAutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 驾照.
        /// </summary>
        public static string TransportOrderMaster_LicenseNo {
            get {
                return ResourceManager.GetString("TransportOrderMaster_LicenseNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 体积(m³).
        /// </summary>
        public static string TransportOrderMaster_LoadVolume {
            get {
                return ResourceManager.GetString("TransportOrderMaster_LoadVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 载重(kg).
        /// </summary>
        public static string TransportOrderMaster_LoadWeight {
            get {
                return ResourceManager.GetString("TransportOrderMaster_LoadWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 放行配载率.
        /// </summary>
        public static string TransportOrderMaster_MinLoadRate {
            get {
                return ResourceManager.GetString("TransportOrderMaster_MinLoadRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 多点提货.
        /// </summary>
        public static string TransportOrderMaster_MultiSitePick {
            get {
                return ResourceManager.GetString("TransportOrderMaster_MultiSitePick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 运单号.
        /// </summary>
        public static string TransportOrderMaster_OrderNo {
            get {
                return ResourceManager.GetString("TransportOrderMaster_OrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 运价单.
        /// </summary>
        public static string TransportOrderMaster_PriceList {
            get {
                return ResourceManager.GetString("TransportOrderMaster_PriceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参考单号.
        /// </summary>
        public static string TransportOrderMaster_ReferenceOrderNo {
            get {
                return ResourceManager.GetString("TransportOrderMaster_ReferenceOrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 始发地.
        /// </summary>
        public static string TransportOrderMaster_ShipFrom {
            get {
                return ResourceManager.GetString("TransportOrderMaster_ShipFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 始发地地址.
        /// </summary>
        public static string TransportOrderMaster_ShipFromAddress {
            get {
                return ResourceManager.GetString("TransportOrderMaster_ShipFromAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目的地.
        /// </summary>
        public static string TransportOrderMaster_ShipTo {
            get {
                return ResourceManager.GetString("TransportOrderMaster_ShipTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目的地地址.
        /// </summary>
        public static string TransportOrderMaster_ShipToAddress {
            get {
                return ResourceManager.GetString("TransportOrderMaster_ShipToAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 状态.
        /// </summary>
        public static string TransportOrderMaster_Status {
            get {
                return ResourceManager.GetString("TransportOrderMaster_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 吨位.
        /// </summary>
        public static string TransportOrderMaster_Tonnage {
            get {
                return ResourceManager.GetString("TransportOrderMaster_Tonnage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 运输方式.
        /// </summary>
        public static string TransportOrderMaster_TransportMode {
            get {
                return ResourceManager.GetString("TransportOrderMaster_TransportMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 运输工具.
        /// </summary>
        public static string TransportOrderMaster_Vehicle {
            get {
                return ResourceManager.GetString("TransportOrderMaster_Vehicle", resourceCulture);
            }
        }
    }
}
