//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.TMS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TransportBillMstr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TransportBillMstr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.TMS.TransportBillMstr", typeof(TransportBillMstr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Billing.
        /// </summary>
        public static string BillMstr_BatchBilling {
            get {
                return ResourceManager.GetString("BillMstr_BatchBilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Address.
        /// </summary>
        public static string BillMstr_BillAddress {
            get {
                return ResourceManager.GetString("BillMstr_BillAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billed Amount.
        /// </summary>
        public static string BillMstr_BilledAmount {
            get {
                return ResourceManager.GetString("BillMstr_BilledAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing.
        /// </summary>
        public static string BillMstr_Billing {
            get {
                return ResourceManager.GetString("BillMstr_Billing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill No.
        /// </summary>
        public static string BillMstr_BillNo {
            get {
                return ResourceManager.GetString("BillMstr_BillNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier.
        /// </summary>
        public static string BillMstr_Carrier {
            get {
                return ResourceManager.GetString("BillMstr_Carrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Date.
        /// </summary>
        public static string BillMstr_CreateDate {
            get {
                return ResourceManager.GetString("BillMstr_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User.
        /// </summary>
        public static string BillMstr_CreateUserName {
            get {
                return ResourceManager.GetString("BillMstr_CreateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Date.
        /// </summary>
        public static string BillMstr_EffectiveDate {
            get {
                return ResourceManager.GetString("BillMstr_EffectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        public static string BillMstr_EndTime {
            get {
                return ResourceManager.GetString("BillMstr_EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ext Bill No.
        /// </summary>
        public static string BillMstr_ExternalBillNo {
            get {
                return ResourceManager.GetString("BillMstr_ExternalBillNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Date.
        /// </summary>
        public static string BillMstr_InvoiceDate {
            get {
                return ResourceManager.GetString("BillMstr_InvoiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice No.
        /// </summary>
        public static string BillMstr_InvoiceNo {
            get {
                return ResourceManager.GetString("BillMstr_InvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string BillMstr_StartTime {
            get {
                return ResourceManager.GetString("BillMstr_StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string BillMstr_Status {
            get {
                return ResourceManager.GetString("BillMstr_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Bill.
        /// </summary>
        public static string BillMstr_Title {
            get {
                return ResourceManager.GetString("BillMstr_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repricing.
        /// </summary>
        public static string BillMstr_ToCalculate {
            get {
                return ResourceManager.GetString("BillMstr_ToCalculate", resourceCulture);
            }
        }
    }
}
