//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.WMS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DeliveryBarCode {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DeliveryBarCode() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.WMS.DeliveryBarCode", typeof(DeliveryBarCode).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BarCode.
        /// </summary>
        public static string DeliveryBarCode_BarCode {
            get {
                return ResourceManager.GetString("DeliveryBarCode_BarCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndDate.
        /// </summary>
        public static string DeliveryBarCode_EndDate {
            get {
                return ResourceManager.GetString("DeliveryBarCode_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsActive.
        /// </summary>
        public static string DeliveryBarCode_IsActive {
            get {
                return ResourceManager.GetString("DeliveryBarCode_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string DeliveryBarCode_Item {
            get {
                return ResourceManager.GetString("DeliveryBarCode_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Description.
        /// </summary>
        public static string DeliveryBarCode_ItemDescription {
            get {
                return ResourceManager.GetString("DeliveryBarCode_ItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastModifyDate.
        /// </summary>
        public static string DeliveryBarCode_LastModifyDate {
            get {
                return ResourceManager.GetString("DeliveryBarCode_LastModifyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastModifyUserName.
        /// </summary>
        public static string DeliveryBarCode_LastModifyUserName {
            get {
                return ResourceManager.GetString("DeliveryBarCode_LastModifyUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationFrom.
        /// </summary>
        public static string DeliveryBarCode_LocationFrom {
            get {
                return ResourceManager.GetString("DeliveryBarCode_LocationFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationTo.
        /// </summary>
        public static string DeliveryBarCode_LocationTo {
            get {
                return ResourceManager.GetString("DeliveryBarCode_LocationTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderNo.
        /// </summary>
        public static string DeliveryBarCode_OrderNo {
            get {
                return ResourceManager.GetString("DeliveryBarCode_OrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartyFrom.
        /// </summary>
        public static string DeliveryBarCode_PartyFrom {
            get {
                return ResourceManager.GetString("DeliveryBarCode_PartyFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartyTo.
        /// </summary>
        public static string DeliveryBarCode_PartyTo {
            get {
                return ResourceManager.GetString("DeliveryBarCode_PartyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BarCode Printed.
        /// </summary>
        public static string DeliveryBarCode_Printed {
            get {
                return ResourceManager.GetString("DeliveryBarCode_Printed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string DeliveryBarCode_Qty {
            get {
                return ResourceManager.GetString("DeliveryBarCode_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReferenceItemCode.
        /// </summary>
        public static string DeliveryBarCode_ReferenceItemCode {
            get {
                return ResourceManager.GetString("DeliveryBarCode_ReferenceItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        public static string DeliveryBarCode_Remark {
            get {
                return ResourceManager.GetString("DeliveryBarCode_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipFrom.
        /// </summary>
        public static string DeliveryBarCode_ShipFrom {
            get {
                return ResourceManager.GetString("DeliveryBarCode_ShipFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipTo.
        /// </summary>
        public static string DeliveryBarCode_ShipTo {
            get {
                return ResourceManager.GetString("DeliveryBarCode_ShipTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartDate.
        /// </summary>
        public static string DeliveryBarCode_StartDate {
            get {
                return ResourceManager.GetString("DeliveryBarCode_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitCount.
        /// </summary>
        public static string DeliveryBarCode_UnitCount {
            get {
                return ResourceManager.GetString("DeliveryBarCode_UnitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitCountDescription.
        /// </summary>
        public static string DeliveryBarCode_UnitCountDescription {
            get {
                return ResourceManager.GetString("DeliveryBarCode_UnitCountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitQty.
        /// </summary>
        public static string DeliveryBarCode_UnitQty {
            get {
                return ResourceManager.GetString("DeliveryBarCode_UnitQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uom.
        /// </summary>
        public static string DeliveryBarCode_Uom {
            get {
                return ResourceManager.GetString("DeliveryBarCode_Uom", resourceCulture);
            }
        }
    }
}
