//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace com.Sconit.Service.SI.WSMes {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSMesSoapBinding", Namespace="http://pandora.realtech.com")]
    public partial class WSMes : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SYNC_POOperationCompleted;
        
        private System.Threading.SendOrPostCallback MATERIAL_IO_BOUNDOperationCompleted;
        
        private System.Threading.SendOrPostCallback RELEASE_MPPOperationCompleted;
        
        private System.Threading.SendOrPostCallback SYNC_SUPPLIEROperationCompleted;
        
        private System.Threading.SendOrPostCallback SYNC_MATERIALOperationCompleted;
        
        private System.Threading.SendOrPostCallback SYNC_CUSTOMEROperationCompleted;
        
        private System.Threading.SendOrPostCallback getMaterialOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSMes() {
            this.Url = global::com.Sconit.Service.SI.Properties.Settings.Default.com_Sconit_Service_SI_WSMes_WSMes;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SYNC_POCompletedEventHandler SYNC_POCompleted;
        
        /// <remarks/>
        public event MATERIAL_IO_BOUNDCompletedEventHandler MATERIAL_IO_BOUNDCompleted;
        
        /// <remarks/>
        public event RELEASE_MPPCompletedEventHandler RELEASE_MPPCompleted;
        
        /// <remarks/>
        public event SYNC_SUPPLIERCompletedEventHandler SYNC_SUPPLIERCompleted;
        
        /// <remarks/>
        public event SYNC_MATERIALCompletedEventHandler SYNC_MATERIALCompleted;
        
        /// <remarks/>
        public event SYNC_CUSTOMERCompletedEventHandler SYNC_CUSTOMERCompleted;
        
        /// <remarks/>
        public event getMaterialCompletedEventHandler getMaterialCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://pandora.realtech.com", ResponseNamespace="http://pandora.realtech.com", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("sync_po_response")]
        public wsResponse SYNC_PO(string po_doc) {
            object[] results = this.Invoke("SYNC_PO", new object[] {
                        po_doc});
            return ((wsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void SYNC_POAsync(string po_doc) {
            this.SYNC_POAsync(po_doc, null);
        }
        
        /// <remarks/>
        public void SYNC_POAsync(string po_doc, object userState) {
            if ((this.SYNC_POOperationCompleted == null)) {
                this.SYNC_POOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSYNC_POOperationCompleted);
            }
            this.InvokeAsync("SYNC_PO", new object[] {
                        po_doc}, this.SYNC_POOperationCompleted, userState);
        }
        
        private void OnSYNC_POOperationCompleted(object arg) {
            if ((this.SYNC_POCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SYNC_POCompleted(this, new SYNC_POCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://pandora.realtech.com", ResponseNamespace="http://pandora.realtech.com", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("material_io_bound_res")]
        public string MATERIAL_IO_BOUND(string material_io_bound_req) {
            object[] results = this.Invoke("MATERIAL_IO_BOUND", new object[] {
                        material_io_bound_req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MATERIAL_IO_BOUNDAsync(string material_io_bound_req) {
            this.MATERIAL_IO_BOUNDAsync(material_io_bound_req, null);
        }
        
        /// <remarks/>
        public void MATERIAL_IO_BOUNDAsync(string material_io_bound_req, object userState) {
            if ((this.MATERIAL_IO_BOUNDOperationCompleted == null)) {
                this.MATERIAL_IO_BOUNDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMATERIAL_IO_BOUNDOperationCompleted);
            }
            this.InvokeAsync("MATERIAL_IO_BOUND", new object[] {
                        material_io_bound_req}, this.MATERIAL_IO_BOUNDOperationCompleted, userState);
        }
        
        private void OnMATERIAL_IO_BOUNDOperationCompleted(object arg) {
            if ((this.MATERIAL_IO_BOUNDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MATERIAL_IO_BOUNDCompleted(this, new MATERIAL_IO_BOUNDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://pandora.realtech.com", ResponseNamespace="http://pandora.realtech.com", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("release_mpp_response")]
        public wsResponse RELEASE_MPP(string mpp_doc) {
            object[] results = this.Invoke("RELEASE_MPP", new object[] {
                        mpp_doc});
            return ((wsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void RELEASE_MPPAsync(string mpp_doc) {
            this.RELEASE_MPPAsync(mpp_doc, null);
        }
        
        /// <remarks/>
        public void RELEASE_MPPAsync(string mpp_doc, object userState) {
            if ((this.RELEASE_MPPOperationCompleted == null)) {
                this.RELEASE_MPPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRELEASE_MPPOperationCompleted);
            }
            this.InvokeAsync("RELEASE_MPP", new object[] {
                        mpp_doc}, this.RELEASE_MPPOperationCompleted, userState);
        }
        
        private void OnRELEASE_MPPOperationCompleted(object arg) {
            if ((this.RELEASE_MPPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RELEASE_MPPCompleted(this, new RELEASE_MPPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://pandora.realtech.com", ResponseNamespace="http://pandora.realtech.com", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("sync_supplier_response")]
        public wsResponse SYNC_SUPPLIER(string supplier_doc) {
            object[] results = this.Invoke("SYNC_SUPPLIER", new object[] {
                        supplier_doc});
            return ((wsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void SYNC_SUPPLIERAsync(string supplier_doc) {
            this.SYNC_SUPPLIERAsync(supplier_doc, null);
        }
        
        /// <remarks/>
        public void SYNC_SUPPLIERAsync(string supplier_doc, object userState) {
            if ((this.SYNC_SUPPLIEROperationCompleted == null)) {
                this.SYNC_SUPPLIEROperationCompleted = new System.Threading.SendOrPostCallback(this.OnSYNC_SUPPLIEROperationCompleted);
            }
            this.InvokeAsync("SYNC_SUPPLIER", new object[] {
                        supplier_doc}, this.SYNC_SUPPLIEROperationCompleted, userState);
        }
        
        private void OnSYNC_SUPPLIEROperationCompleted(object arg) {
            if ((this.SYNC_SUPPLIERCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SYNC_SUPPLIERCompleted(this, new SYNC_SUPPLIERCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://pandora.realtech.com", ResponseNamespace="http://pandora.realtech.com", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("sync_material_response")]
        public wsResponse SYNC_MATERIAL(string material_doc) {
            object[] results = this.Invoke("SYNC_MATERIAL", new object[] {
                        material_doc});
            return ((wsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void SYNC_MATERIALAsync(string material_doc) {
            this.SYNC_MATERIALAsync(material_doc, null);
        }
        
        /// <remarks/>
        public void SYNC_MATERIALAsync(string material_doc, object userState) {
            if ((this.SYNC_MATERIALOperationCompleted == null)) {
                this.SYNC_MATERIALOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSYNC_MATERIALOperationCompleted);
            }
            this.InvokeAsync("SYNC_MATERIAL", new object[] {
                        material_doc}, this.SYNC_MATERIALOperationCompleted, userState);
        }
        
        private void OnSYNC_MATERIALOperationCompleted(object arg) {
            if ((this.SYNC_MATERIALCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SYNC_MATERIALCompleted(this, new SYNC_MATERIALCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://pandora.realtech.com", ResponseNamespace="http://pandora.realtech.com", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("sync_customer_response")]
        public wsResponse SYNC_CUSTOMER(string customer_doc) {
            object[] results = this.Invoke("SYNC_CUSTOMER", new object[] {
                        customer_doc});
            return ((wsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void SYNC_CUSTOMERAsync(string customer_doc) {
            this.SYNC_CUSTOMERAsync(customer_doc, null);
        }
        
        /// <remarks/>
        public void SYNC_CUSTOMERAsync(string customer_doc, object userState) {
            if ((this.SYNC_CUSTOMEROperationCompleted == null)) {
                this.SYNC_CUSTOMEROperationCompleted = new System.Threading.SendOrPostCallback(this.OnSYNC_CUSTOMEROperationCompleted);
            }
            this.InvokeAsync("SYNC_CUSTOMER", new object[] {
                        customer_doc}, this.SYNC_CUSTOMEROperationCompleted, userState);
        }
        
        private void OnSYNC_CUSTOMEROperationCompleted(object arg) {
            if ((this.SYNC_CUSTOMERCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SYNC_CUSTOMERCompleted(this, new SYNC_CUSTOMERCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://pandora.realtech.com", ResponseNamespace="http://pandora.realtech.com", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("result_material")]
        public material getMaterial(string material_code) {
            object[] results = this.Invoke("getMaterial", new object[] {
                        material_code});
            return ((material)(results[0]));
        }
        
        /// <remarks/>
        public void getMaterialAsync(string material_code) {
            this.getMaterialAsync(material_code, null);
        }
        
        /// <remarks/>
        public void getMaterialAsync(string material_code, object userState) {
            if ((this.getMaterialOperationCompleted == null)) {
                this.getMaterialOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMaterialOperationCompleted);
            }
            this.InvokeAsync("getMaterial", new object[] {
                        material_code}, this.getMaterialOperationCompleted, userState);
        }
        
        private void OngetMaterialOperationCompleted(object arg) {
            if ((this.getMaterialCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMaterialCompleted(this, new getMaterialCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pandora.realtech.com")]
    public partial class wsResponse {
        
        private int errorCodeField;
        
        private string errorMsgField;
        
        private object[] failureSetField;
        
        private string idFieldNameField;
        
        private string replierField;
        
        private string replyDateField;
        
        private string replyIdField;
        
        private object[] successSetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string errorMsg {
            get {
                return this.errorMsgField;
            }
            set {
                this.errorMsgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("failureSet", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public object[] failureSet {
            get {
                return this.failureSetField;
            }
            set {
                this.failureSetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string idFieldName {
            get {
                return this.idFieldNameField;
            }
            set {
                this.idFieldNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string replier {
            get {
                return this.replierField;
            }
            set {
                this.replierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string replyDate {
            get {
                return this.replyDateField;
            }
            set {
                this.replyDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string replyId {
            get {
                return this.replyIdField;
            }
            set {
                this.replyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("successSet", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public object[] successSet {
            get {
                return this.successSetField;
            }
            set {
                this.successSetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pandora.realtech.com")]
    public partial class material {
        
        private string codeField;
        
        private string idField;
        
        private string modelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    public delegate void SYNC_POCompletedEventHandler(object sender, SYNC_POCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SYNC_POCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SYNC_POCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public wsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((wsResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    public delegate void MATERIAL_IO_BOUNDCompletedEventHandler(object sender, MATERIAL_IO_BOUNDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MATERIAL_IO_BOUNDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MATERIAL_IO_BOUNDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    public delegate void RELEASE_MPPCompletedEventHandler(object sender, RELEASE_MPPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RELEASE_MPPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RELEASE_MPPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public wsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((wsResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    public delegate void SYNC_SUPPLIERCompletedEventHandler(object sender, SYNC_SUPPLIERCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SYNC_SUPPLIERCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SYNC_SUPPLIERCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public wsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((wsResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    public delegate void SYNC_MATERIALCompletedEventHandler(object sender, SYNC_MATERIALCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SYNC_MATERIALCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SYNC_MATERIALCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public wsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((wsResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    public delegate void SYNC_CUSTOMERCompletedEventHandler(object sender, SYNC_CUSTOMERCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SYNC_CUSTOMERCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SYNC_CUSTOMERCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public wsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((wsResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    public delegate void getMaterialCompletedEventHandler(object sender, getMaterialCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMaterialCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMaterialCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public material Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((material)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591