IF EXISTS(SELECT * FROM sys.types WHERE name='REC_CNMT_INPUT') 
	DROP TYPE [dbo].[REC_CNMT_INPUT]
GO

CREATE TYPE [dbo].[REC_CNMT_INPUT] AS TABLE(
	REC_LN INT,
	PUR_PL_ID INT,
	CNMT_QTY DECIMAL(18, 8),
	ORD_LN INT,
	DVL_LN INT
)
GO

