IF EXISTS(SELECT * FROM sys.types WHERE name='ERR_MSG_OUTPUT') 
	DROP TYPE [dbo].[ERR_MSG_OUTPUT]
GO

CREATE TYPE [dbo].[ERR_MSG_OUTPUT] AS TABLE(
	LVL CHAR(1),
	MSG NVARCHAR(500)
)
GO

IF EXISTS(SELECT * FROM sys.types WHERE name='PREP_REC_CNMT_INPUT') 
	DROP TYPE [dbo].[PREP_REC_CNMT_INPUT]
GO

CREATE TYPE [dbo].[PREP_REC_CNMT_INPUT] AS TABLE(
	PUR_PL_ID INT,
	ORD_LN INT,
	DLV_LN INT,
	REC_LN INT,
	CNMT_QTY DECIMAL(18, 8)
)
GO

IF EXISTS(SELECT * FROM sys.types WHERE name='REC_CNMT_INPUT') 
	DROP TYPE [dbo].[REC_CNMT_INPUT]
GO

CREATE TYPE [dbo].[REC_CNMT_INPUT] AS TABLE(
	PUR_PL_ID INT PRIMARY KEY,
	SUPPL_CD VARCHAR(20),
	ORD_LN INT,
	DLV_LN INT,
	REC_LN INT,
	PT_NO VARCHAR(20),
	UOM VARCHAR(3),
	BASE_UOM VARCHAR(3),
	UOM_CONV_RT DECIMAL(18, 8),
	CNMT_QTY DECIMAL(18, 8),
	VER INT
)
GO

--IF EXISTS(SELECT * FROM sys.types WHERE name='REC_CNMT_BAR_CD_INPUT') 
--	DROP TYPE [dbo].[REC_CNMT_BAR_CD_INPUT]
--GO

--CREATE TYPE [dbo].[REC_CNMT_BAR_CD_INPUT] AS TABLE(
--	REC_LN INT,
--	BAR_CD VARCHAR(20),
--	CNMT_QTY DECIMAL(18, 8)
--)
--GO

