SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

IF EXISTS(SELECT * FROM sys.objects WHERE type='P' AND name='USP_NEXT_SEQ') 
     DROP PROCEDURE [USP_NEXT_SEQ] 
GO

CREATE PROCEDURE [dbo].[USP_NEXT_SEQ] 
(
	@SEQ_PREFIX VARCHAR(20), 
	@NEXT_SEQ BIGINT OUTPUT 
) --WITH ENCRYPTION
AS 
BEGIN
	SET NOCOUNT ON 

	DECLARE @SEQ_TBL_NM VARCHAR(50) = 'SEQ_' + @SEQ_PREFIX

	IF NOT EXISTS(SELECT TOP 1 1 FROM sys.objects WHERE TYPE='U' AND name= @SEQ_TBL_NM)
	BEGIN
		DECLARE @CRT_TBL_STAT nvarchar(200) = 'CREATE TABLE ' + @SEQ_TBL_NM + '(ID BIGINT IDENTITY(1,1) NOT NULL)'
		EXEC sp_executesql @CRT_TBL_STAT
	END
	
	DECLARE @INS_STAT nvarchar(400) = '
	DECLARE @TRNAS_CNT INT = @@TRANCOUNT

	IF @TRNAS_CNT > 0
	BEGIN
		SAVE TRAN SP_NEXT_SEQ
    END
    ELSE
    BEGIN
		BEGIN TRAN NEXT_SEQ
    END

	INSERT INTO ' + @SEQ_TBL_NM + N' DEFAULT VALUES
	SELECT @NEXT_SEQ = SCOPE_IDENTITY()

	IF @TRNAS_CNT > 0
	BEGIN
		ROLLBACK TRAN SP_NEXT_SEQ
    END
	ELSE
    BEGIN
		ROLLBACK TRAN NEXT_SEQ
	END'

	EXEC sp_executesql @INS_STAT, N'@NEXT_SEQ BIGINT OUTPUT', @NEXT_SEQ OUTPUT
END
