SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

IF EXISTS(SELECT * FROM sys.objects WHERE type='P' AND name='USP_PREP_REC_CNMT') 
     DROP PROCEDURE [USP_PREP_REC_CNMT] 
GO

CREATE PROCEDURE [dbo].[USP_PREP_REC_CNMT] 
AS 
BEGIN
	SET NOCOUNT ON

	DECLARE @ERROR_MSG NVARCHAR(MAX)

	BEGIN TRY
		IF NOT EXISTS(SELECT TOP 1 1 FROM tempdb.sys.objects WHERE type = 'U' AND name LIKE '#TMP_REC_CNMT_INPUT')
		BEGIN
			SET @ERROR_MSG = '没有定义临时表#TMP_REC_CNMT_INPUT表。'
			RAISERROR(@ERROR_MSG, 16, 1) 

			--
			CREATE TABLE #TMP_REC_CNMT_INPUT (
				VOU_LN INT PRIMARY KEY,
				SUPPL_CD VARCHAR(20),
				ORD_LN INT,
				DLV_LN INT,
				PUR_PL_ID INT,
				PT_NO VARCHAR(20),
				UOM VARCHAR(3),
				BASE_UOM VARCHAR(3),
				UOM_CONV_RT DECIMAL(18, 8),
				CNMT_QTY DECIMAL(18, 8),
				VER INT
			)
		END

		IF NOT EXISTS(SELECT TOP 1 1 FROM #TMP_REC_CNMT_INPUT)
		BEGIN
			--采购收货记录为空
			SET @ERROR_MSG = N'寄售物料明细不能为空。'
			RAISERROR(@ERROR_MSG, 16, 1) 
		END
		ELSE BEGIN
			UPDATE A SET VER = B.VER
			FROM #TMP_REC_CNMT_INPUT AS A
			LEFT JOIN CNMT_BN AS B ON A.PUR_PL_ID = B.PUR_PL_ID
		END
	END TRY
	BEGIN CATCH
		SET @ERROR_MSG = N'程序执行时发生错误:' + ERROR_MESSAGE() + N'，行数：' + ERROR_LINE()
		RAISERROR(@ERROR_MSG, 16, 1) 
	END CATCH
END
GO