SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

IF EXISTS(SELECT * FROM sys.objects WHERE type='P' AND name='USP_REC_CNMT') 
     DROP PROCEDURE [USP_REC_CNMT] 
GO

CREATE PROCEDURE [dbo].[USP_REC_CNMT] 
(
	@VOU_NO VARCHAR(20),
	@ORD_NO VARCHAR(20),
	@ORD_TP CHAR(1),
	@DLV_NO VARCHAR(20),
	@EFF_DT DATE,
	@CRT_USR_CD VARCHAR(20)
) --WITH ENCRYPTION
AS 
BEGIN
	SET NOCOUNT ON

	DECLARE @ERROR_MSG NVARCHAR(MAX)
	DECLARE @DATETIME_NOW DATETIME
	DECLARE @INS_CNT INT
	DECLARE @CNMT_TRANS_ID INT

	SET @DATETIME_NOW = GETDATE()

	IF @EFF_DT IS NULL
	BEGIN
		SET @EFF_DT = CONVERT(VARCHAR(10), @DATETIME_NOW, 120)
	END

	BEGIN TRY
		IF NOT EXISTS(SELECT TOP 1 1 FROM tempdb.sys.objects WHERE type = 'U' AND name LIKE '#TMP_REC_CNMT_INPUT')
		BEGIN
			SET @ERROR_MSG = '没有定义临时表#TMP_REC_CNMT_INPUT表。'
			RAISERROR(@ERROR_MSG, 16, 1) 

			--
			CREATE TABLE #TMP_REC_CNMT_INPUT (
				PUR_PL_ID INT PRIMARY KEY,
				SUPPL_CD VARCHAR(20),
				ORD_LN INT,
				DLV_LN INT,
				VOU_LN INT,
				PT_NO VARCHAR(20),
				UOM VARCHAR(3),
				BASE_UOM VARCHAR(3),
				UOM_CONV_RT DECIMAL(18, 8),
				CNMT_QTY DECIMAL(18, 8),
				VER INT
			)
		END

		SELECT @INS_CNT = COUNT(1) FROM #TMP_REC_CNMT_INPUT WHERE VER IS NULL

		UPDATE A SET CNMT_QTY = A.CNMT_QTY + B.CNMT_QTY
		FROM CNMT_BN AS A INNER JOIN #TMP_REC_CNMT_INPUT AS B ON A.PUR_PL_ID = B.PUR_PL_ID AND A.VER = B.VER

		IF (@@ROWCOUNT <> @INS_CNT)
		BEGIN
			RAISERROR(60005, 16, 1)
		END

		INSERT INTO CNMT_BN(PUR_PL_ID, SUPPL_CD, PT_NO, UOM, BASE_UOM, UOM_CONV_RT, CNMT_QTY, STL_QTY, VER)
		SELECT PUR_PL_ID, SUPPL_CD, PT_NO, UOM, BASE_UOM, UOM_CONV_RT, CNMT_QTY, 0, 1 
		FROM #TMP_REC_CNMT_INPUT WHERE VER IS NULL

		INSERT INTO CNMT_TRANS(ORD_NO, ORD_TP, DLV_NO, VOU_NO, EFF_DT, IS_VD, CRT_DT, CRT_USR_CD)
		VALUES(@ORD_NO, @ORD_TP, @DLV_NO, @VOU_NO, @EFF_DT, 0, @DATETIME_NOW, @CRT_USR_CD)

		SET @CNMT_TRANS_ID = @@IDENTITY

		INSERT INTO CNMT_TRANS_DET(CNMT_TRANS_ID, CNMT_TRANS_LN, ORD_LN, DLV_LN, PUR_PL_ID, PT_NO, UOM, BASE_UOM, UOM_CONV_RT, CNMT_QTY)
		SELECT @CNMT_TRANS_ID, VOU_LN, ORD_LN, DLV_LN, PUR_PL_ID, PT_NO, UOM, BASE_UOM, UOM_CONV_RT, CNMT_QTY 
		FROM #TMP_REC_CNMT_INPUT
	END TRY
	BEGIN CATCH
		SET @ERROR_MSG = N'程序执行时发生错误:' + ERROR_MESSAGE() + N'，行数：' + ERROR_LINE()
		RAISERROR(@ERROR_MSG, 16, 1) 
	END CATCH
END
GO