SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

IF EXISTS(SELECT * FROM sys.objects WHERE type='P' AND name='.USP_PREP_REC_INV_IN') 
     DROP PROCEDURE [USP_PREP_REC_INV_IN] 
GO

CREATE PROCEDURE [dbo].[USP_PREP_REC_INV_IN] 
AS 
BEGIN
	SET NOCOUNT ON

	DECLARE @ERROR_MSG NVARCHAR(MAX)

	BEGIN TRY
		IF NOT EXISTS(SELECT TOP 1 1 FROM tempdb.sys.objects WHERE type = 'U' AND name LIKE '#TMP_REC_INV_IN_INPUT')
		BEGIN
			SET @ERROR_MSG = '没有定义临时表#TMP_REC_INV_IN_INPUT表。'
			RAISERROR(@ERROR_MSG, 16, 1) 

			--收货入库输入参数表
			CREATE TABLE #TMP_REC_INV_IN_INPUT (
				VOU_LN INT PRIMARY KEY,
				ORD_LN INT,
				DLV_LN INT,
				PT_NO VARCHAR(20),
				UOM VARCHAR(3),
				BASE_UOM VARCHAR(3),
				UOM_CONV_RT DECIMAL(18, 8),
				LOC_CD VARCHAR(20),
				QLTY_TP CHAR(1),
				IS_FRZ BIT,
				IS_BC BIT,
				IS_TR BIT,
				IS_CNMT BIT,
				QTY DECIMAL(18, 8),
				RSN_CD CHAR(3),
				INV_BN_ID INT,
				VER INT
			)

			--条码入库输入参数表
			CREATE TABLE #TMP_REC_INV_IN_BC_INPUT (
				BAR_CD VARCHAR(20) PRIMARY KEY,
				VOU_LN INT,
				QTY DECIMAL(18, 8),
				UOM VARCHAR(3),
				BASE_UOM VARCHAR(3),
				UOM_CONV_RT DECIMAL(18, 8)
			)
		END

	
	END TRY
	BEGIN CATCH
		SET @ERROR_MSG = N'程序执行时发生错误:' + ERROR_MESSAGE() + N'，行数：' + ERROR_LINE()
		RAISERROR(@ERROR_MSG, 16, 1) 
	END CATCH
END
GO