SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

IF EXISTS(SELECT * FROM sys.objects WHERE type='P' AND name='USP_RECORD_INV') 
     DROP PROCEDURE [USP_RECORD_INV] 
GO

CREATE PROCEDURE [dbo].[USP_RECORD_INV] 
(
	@VOU_NO VARCHAR(20),
	@ORD_NO VARCHAR(20),
	@ORD_TP CHAR(1),
	@EFF_DT DATE,
	@CRT_USR_CD VARCHAR(20)
) --WITH ENCRYPTION
AS 
BEGIN
	SET NOCOUNT ON

	DECLARE @ERROR_MSG NVARCHAR(MAX)
	DECLARE @DATETIME_NOW DATETIME
	DECLARE @BIL_STL_ID INT

	SET @DATETIME_NOW = GETDATE()

	IF @EFF_DT IS NULL
	BEGIN
		SET @EFF_DT = CONVERT(VARCHAR(10), @DATETIME_NOW, 120)
	END

	BEGIN TRY
		IF NOT EXISTS(SELECT TOP 1 1 FROM tempdb.sys.objects WHERE type = 'U' AND name LIKE '#TMP_REC_BIL_STL_INPUT')
		BEGIN
			SET @ERROR_MSG = '没有定义临时表#TMP_REC_BIL_STL_INPUT表。'
			RAISERROR(@ERROR_MSG, 16, 1) 

			--
			CREATE TABLE #TMP_REC_BIL_STL_INPUT (
				VOU_LN INT PRIMARY KEY,
				ORD_LN INT,
				ORD_BOM_ID BIGINT,
				PUR_PL_ID INT,
				PT_NO VARCHAR(20),
				UOM VARCHAR(3),
				BASE_UOM VARCHAR(3),
				UOM_CONV_RT DECIMAL(18, 8),
				STL_QTY DECIMAL(18, 8)
			)
		END

		INSERT INTO BIL_STL(ORD_NO, ORD_TP, VOU_NO, EFF_DT, CRT_DT, CRT_USR_CD)
		VALUES(@ORD_NO, @ORD_TP, @VOU_NO, @EFF_DT, @DATETIME_NOW, @CRT_USR_CD)
	
		INSERT INTO BIL_STL_DET(BIL_STL_LN, ORD_LN, ORD_BOM_ID, VOU_LN, PUR_PL_ID, PT_NO, UOM, BASE_UOM, UOM_CONV_RT, STL_QTY, BIL_STL_STAT, VER)
		SELECT VOU_LN, ORD_LN, ORD_BOM_ID, VOU_LN, PUR_PL_ID, PT_NO, UOM, BASE_UOM, UOM_CONV_RT, STL_QTY, 'A', 1
		FROM #TMP_REC_BIL_STL_INPUT
	END TRY
	BEGIN CATCH
		SET @ERROR_MSG = N'程序执行时发生错误:' + ERROR_MESSAGE() + N'，行数：' + ERROR_LINE()
		RAISERROR(@ERROR_MSG, 16, 1) 
	END CATCH
END
GO